ALL_VALID: False

DESCRIPTION_KEYWORDS_I:
- privilege escalation
- escalation
- privesc
- high integrity
- elevated privilege
- escalation of privilege
- privilege escalation
- " sudo "
- " suid "
- " pe "
- " UAC "
- " lxc "
- buffer overflow
- User Account Control
- Access Control vulnerability
- remote command execution
- command injection vulnerability
- code execution
- denial of service
- authentication bypass
- file inclusion
- XXE
- XML External Entity
- SQL injection
- SQLi
- Cross-Site-Scripting
- Cross Site Scripting
- Cross-Site Scripting
- XSS

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- amazon
- aws
- atlassian
- apple
- azure
- Asus
- container
- docker
- Git
- Github
- kubernetes
- lxc
- Linksys
- PLC
- MySQL 
- MSSQL
- npm
- python
- podman
- NoSQL
- SQL
- TPlink
- sudo
- SCADA
- kubernetes
- wordpress

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample


