ALL_VALID: False

DESCRIPTION_KEYWORDS_I:
- privilege escalation
- escalation
- privesc
- high integrity
- elevated privilege
- escalation of privilege
- privilege escalation
- " sudo "
- " suid "
- " pe "
- " UAC "
- User Account Control
- docker
- kubernetes
- " lxc "
- podman
- remote command execution
- command injection vulnerability
- denial of service
- buffer overflow

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- sudo
- docker
- kubernetes
- lxc
- podman
- container
- amazon
- aws
- atlassian
- apple
- azure
- wordpress

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample


