ALL_VALID: False

DESCRIPTION_KEYWORDS_I:
- " lxc "
- " pe "
- " sudo "
- " suid "
- " UAC "
- access control vulnerability
- authentication
- authorisation
- authorised
- authorization
- authorized
- api
- buffer overflow
- bypass
- code execution
- command injection vulnerability
- cross site 
- cross-site
- csrf
- denial of service
- dom
- default password
- default credential
- default key
- elevated privilege
- escalation of privilege
- enumeration
- file inclusion
- file upload
- forge
- high integrity
- hardcoded credential
- hard coded credential
- hardcoded password
- hard coded password
- hardcoded key
- hard coded key
- idor
- injection
- insecure direct object reference
- insecure permission
- json web token
- jwt
- man in the middle
- man-in-the-middle
- mitm
- open redirect
- oauth
- out of bounds
- out-of-bounds
- out of date
- outdated
- path traversal
- pollution
- privesc
- privilege escalation
- puzzling
- race condition
- rce
- remote command execution
- request forgery
- resource manipulation
- session hijack
- smuggling
- spoofing
- ssrf
- sql injection
- sqli
- takeover
- template injection
- upload
- user account control
- variable overloading
- verb tampering
- xml external entity
- xss
- xxe

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- amazon
- apache
- apple
- asus
- atlassian
- aws
- azure
- chrome
- cloud
- container
- curl
- docker
- git
- github
- google
- java
- kotlin
- kubernetes
- linksys
- lxc
- microsoft
- mssql
- mysql 
- nosql
- npm
- opc
- plc
- podman
- printer
- pypi
- python
- scada
- samsung
- sharepoint
- onedrive
- signal
- sudo
- telegram
- tplink
- whatsapp
- wordpress
- svg

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample


