ALL_VALID: False

DESCRIPTION_KEYWORDS_I:
- privilege escalation
- escalation
- privesc
- high integrity
- elevated privilege
- escalation of privilege
- privilege escalation
- " sudo "
- " suid "
- " pe "
- " UAC "
- " lxc "
- buffer overflow
- User Account Control
- Access Control vulnerability
- remote command execution
- command injection vulnerability
- code execution
- injection
- denial of service
- authentication bypass
- file inclusion
- XXE
- XML External Entity
- SQL injection
- SQLi
- Cross-Site
- Cross Site 
- Cross-Site
- XSS
- Dom
- Request Forgery
- Smuggling
- Pollution
- Session hijack
- direct Object Reference
- IDOR
- Open redirect
- Variable Overloading
- Puzzling
- resource manipulation
- race condition

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- amazon
- aws
- atlassian
- apple
- azure
- Asus
- apache
- container
- docker
- Git
- Github
- java
- kubernetes
- lxc
- Linksys
- PLC
- MySQL 
- MSSQL
- npm
- python
- podman
- NoSQL
- SQL
- TPlink
- sudo
- SCADA
- kubernetes
- wordpress
- whatsapp
- signal
- Google
- telegram

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample


