ALL_VALID: False

DESCRIPTION_KEYWORDS_I:
- " lxc "
- " pe "
- " sudo "
- " suid "
- " UAC "
- access control vulnerability
- api
- authentication
- authorisation
- authorised
- authorization
- authorized
- buffer overflow
- bypass
- code execution
- code injection vulnerability
- command injection vulnerability
- cross site 
- cross-site
- csrf
- default credential
- default key
- default password
- denial of service
- directory traversal
- dom
- elevated privilege
- elevation of privilege
- enumeration
- escalation of privilege
- file inclusion
- file upload
- forge
- hard coded credential
- hard coded key
- hard coded password
- hardcoded credential
- hardcoded key
- hardcoded password
- high integrity
- idor
- injection
- insecure direct object reference
- insecure permission
- json web token
- jwt
- man in the middle
- man-in-the-middle
- mitm
- oauth
- open redirect
- out of bounds
- out of date
- outdated
- out-of-bounds
- path traversal
- pollution
- privesc
- privilege escalation
- puzzling
- race condition
- rce
- remote code execution
- remote command execution
- request forgery
- resource manipulation
- session hijack
- smuggling
- spoofing
- sql injection
- sqli
- ssrf
- takeover
- template injection
- unauthorized operations 
- upload
- user account control
- variable overloading
- verb tampering
- xml external entity
- xss
- xxe

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- amazon
- apache
- apple
- asus
- atlassian
- aws
- azure
- business_objects_business_intelligence_platform
- chrome
- cloud
- container
- curl
- docker
- git
- github
- google
- java
- kotlin
- kubernetes
- linksys
- lxc
- microsoft
- mssql
- mysql 
- netweaver_application_server_for_java
- nosql
- npm
- onedrive
- opc
- plc
- podman
- printer
- pypi
- python
- samsung
- scada
- sharepoint
- signal
- sudo
- telegram
- tplink
- whatsapp
- wordpress

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample


