ALL_VALID: False

DESCRIPTION_KEYWORDS_I:
- " lxc "
- " pe "
- " sudo "
- " suid "
- " UAC "
- access control vulnerability
- authentication
- authorisation
- authorised
- authorization
- authorized
- buffer overflow
- bypass
- code execution
- command injection vulnerability
- cross site 
- cross-site
- denial of service
- dom
- elevated privilege
- escalation
- file inclusion
- high integrity
- idor
- injection
- insecure direct object reference
- open redirect
- out of bounds
- out-of-bounds
- pollution
- privesc
- privilege
- puzzling
- race condition
- rce
- remote command execution
- request forgery
- resource manipulation
- session hijack
- smuggling
- sql injection
- sqli
- upload
- user account control
- variable overloading
- verb tampering
- XML External Entity
- xss
- XXE

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- amazon
- apache
- apple
- Asus
- atlassian
- aws
- azure
- chrome
- container
- docker
- git
- github
- google
- java
- kubernetes
- kubernetes
- linksys
- lxc
- microsoft
- mssql
- mysql 
- nosql
- npm
- opc
- plc
- podman
- pypi
- python
- scada
- signal
- sudo
- telegram
- tplink
- whatsapp
- wordpress

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample


